name: Test and check build

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev", "hotfix" ]

jobs:
  build:

    runs-on: macos-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v3
      - uses: hannesa2/action-android/install-sdk@release/0.1.4.10

        with:
          fetch-depth: "0"
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit test
        run: ./gradlew testDebugUnitTest
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
      - name: Build
        run: ./gradlew :app:assembleDebug
